### ISSUE TITLE
Error: The site does not have the required permissions for this action

### ISSUE THREAD

**Issue by gitjeet** [DanMacDonald/public-square-app#2]
error when posting the post

**Comment by gitjeet** [comment]
> error when posting the post

Error: The site does not have the required permissions for this action

**Comment by DanMacDonald** [comment]
Yes, we've been observing a partial outage at the arweave.net gateway for the last two days that is affecting posting messages. There's not much we can do on the dApp side but wait for it to be resolved.

**Comment by DanMacDonald** [comment]
Hi @gitjeet, on further investigation I discovered we weren't requesting the `DISPATCH` permission from ArConnect.  Posting with ArConnect should be working now.

**Comment by DanMacDonald** [comment]
To anyone who encounters this in the future, your ArConnect wallet initialization should look like this...
https://github.com/DanMacDonald/public-square-app/blob/finished/src/components/WalletSelectButton.jsx#L70

```js
await window.arweaveWallet.connect(['ACCESS_ADDRESS','SIGN_TRANSACTION','DISPATCH']);
```
